BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_rl.yaml
TRAINER_NAME: ddppo-rl
ENV_NAME: VLNCEWaypointEnv
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
BATCHSIZE: 128
NUM_ENVIRONMENTS: 16
TENSORBOARD_DIR: data/tensorboard_dirs/220222_1
CHECKPOINT_FOLDER: data/checkpoints/220222_1
EVAL_CKPT_PATH_DIR: data/checkpoints/220222_1
VISIBLE_GPUS: [4,5,6,7]
MASTER_PORT: 19988
RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: []

  PPO:
    # pano_entropy_coef: 1.5
    entropy_coef: 0.1



  DDPPO:
    pretrained: False
    # pretrained_weights: data/HPN.pth
    # pretrained_weights: data/checkpoints/hpn___baseline_c_1/ckpt.117.pth
    
MODEL:
  policy_name: CMAPolicyRL


  INSTRUCTION_ENCODER:
    bidirectional: True

  # RGB_ENCODER:
  #   cnn_type: TorchVisionResNet18
  #   output_size: 128

  # STATE_ENCODER:
  #   hidden_size: 256
